# Generated by Django 5.1.1 on 2024-10-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('vendor_code', models.TextField(blank=True, max_length=1000)),
                ('imt_name', models.TextField(blank=True, max_length=1000)),
                ('contents', models.TextField(blank=True, max_length=1000)),
                ('slug', models.TextField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
